server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rockeseat
    username: postgres
    password: Luiz1992@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    upd
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

